name: 'Cycle Check'

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - 'srcpkgs/**'

jobs:
  cycles:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || ( github.event_name == 'schedule' && github.repository_owner == 'void-linux' ) }}
    permissions:
      issues: write
    container:
      image: 'ghcr.io/void-linux/void-buildroot-musl:20230904R2'
      env:
        PATH: '/usr/libexec/chroot-git:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'
    steps:
      - name: Prepare container
        run: |
          # switch to repo-ci mirror
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          # Sync and upgrade once, assume error comes from xbps update
          xbps-install -Syu || xbps-install -yu xbps
          # Upgrade again (in case there was a xbps update)
          xbps-install -yu
          # Install script dependencies
          xbps-install -y python3-networkx github-cli

      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Create hostrepo and prepare masterdir
        run: |
          ln -s "$(pwd)" /hostrepo &&
          common/travis/set_mirror.sh &&
          common/travis/prepare.sh

      - name: Restore dependency cache
        run: |
          set -x
          mkdir -p "$GITHUB_WORKSPACE/xbps-cycles"

          run="$(gh run list --status completed --event schedule --workflow cycles.yml --limit 1 --json databaseId --jq '.[].databaseId')"
          if [ -n "$run" ]; then
            gh run download "$run" -D "$GITHUB_WORKSPACE/xbps-cycles" -n dependency-cache || true
          fi
          ls -l "$GITHUB_WORKSPACE/xbps-cycles"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Find cycles
        run: |
          common/scripts/xbps-cycles.py -c "$GITHUB_WORKSPACE/xbps-cycles" | tee cycles

      - name: Open issues
        if: ${{ github.event_name == 'schedule' }}
        run: |
          grep 'Cycle:' cycles | while read -r line; do
              if gh issue list -R "$GITHUB_REPOSITORY" -S "$line" | grep .; then
                  printf "Issue on '%s' already exists.\n" "$line"
              else
                  gh issue create -R "$GITHUB_REPOSITORY" -b '' -t "$line"
              fi
          done
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          if grep -q '^Cycle:' cycles; then
            echo "Build cycles found:"
            rv=1
          else
            echo "No cycles found:"
            rv=0
          fi
          cat cycles
          exit $rv

      - name: Save dependency cache
        uses: actions/upload-artifact@v1
        with:
          name: dependency-cache
          path: xbps-cycles
