name: Check Manual Changes

on:
  pull_request:
    paths:
      - 'Manual.md'
      - 'manual/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manual:
    name: Check links
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl:20231230R1
    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y git bash mdBook mdbook-linkcheck
      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - run: ./common/travis/manual-ci.sh

